package net.kiranatos.model;

public enum NamePartLanguage {
    adjective,
    adverb,
    attributive,
    conjunction,
    comparative,
    emphatic_pronoun,
    imperative,
    INTERJECTION,
    NOUN, 
    NUMERAL, 
    PARTICLE,
    PASSIVE,
    plural,
    past_participle,
    predicative,
    prefix,
    preposition,
    present_participle,
    pronoun,
    reflexive,
    singular,
    somebody,
    something,
    suffix,
    superlative,
    verb
}
